### PR TITLE
#121 Added tag types to the Paste type

### LINKED ISSUE #121: Add specific tag on posts
Allow the user to pick what type of tag they want on their posts: public, private, or unlisted. This way the posts can be categorized.

### PR DESCRIPTION
**Pull request by Archana90663**
Added post tag types such as Public, Private, and Unlisted to the Paste class and interfaces. Also added them in the backend. 

Resolves #121 and #122

### CODE REVIEW

**Comment by paramgupta107** [comment]
> Added post tag types such as Public, Private, and Unlisted to the Paste class and interfaces. Also added them in the backend.
> 
> Resolves #121 and #122

There are no changes in the backend

**Review by bkojusner — APPROVED** [review]
LGTM

**Comment by Archana90663** [comment]
> > Added post tag types such as Public, Private, and Unlisted to the Paste class and interfaces. Also added them in the backend.
> > Resolves #121 and #122
> 
> There are no changes in the backend

That's odd... I had made changes to it. Let me try committing it again

**Comment by Archana90663** [comment]
> > > Added post tag types such as Public, Private, and Unlisted to the Paste class and interfaces. Also added them in the backend.
> > > Resolves #121 and #122
> > 
> > 
> > There are no changes in the backend
> 
> That's odd... I had made changes to it. Let me try committing it again

Okay merging this but creating a separate branch for the back-end part

**Pull request merged**
