### PR TITLE
#113 created file Sprint1.md

### LINKED ISSUE #113: File describing what was accomplished in Sprint 1
We need to have a Sprint1.md file in our repo that explains what was accomplished in sprint 1

### PR DESCRIPTION
**Pull request by Archana90663**
Created a new file called Sprint1.md which specifies what we accomplished in Sprint 1.

Resolves #113

### CODE REVIEW

**Comment by SudhanshuTarale** [comment]
@Archana90663 maybe for point 9 we can also add that detailed information about the routes implemented can be found at the Github Wiki. Everting else looks good to me!

**Comment by paramgupta107** [comment]
There are several more things to add such as:-

- We created a cronjob in go to periodically purge data of expired posts.
- Setup go embed to create a single executable with the frontend within the binary
- Created a makefile that builds the entire project into one executable.
- Implemented the collection of basic metadata relating to pastes.
- Added a visual feature that displays the expiry date in a more readable way(instead of date calculate a string like `expire in: 3 days` or `expire in: 23 hours`.

If the number of points seems too much then keep the most important ones.

**Comment by paramgupta107** [comment]
also,

- implemented a routing system to be able to create a sharable link of a post with proper error handling in case of expired posts.
- Detailed documentation of backend route.
- Propper documentation of usage of app with gifs (we will do this today)

**Comment by Archana90663** [comment]
> There are several more things to add such as:-
> 
> * We created a cronjob in go to periodically purge data of expired posts.
> * Setup go embed to create a single executable with the frontend within the binary
> * Created a makefile that builds the entire project into one executable.
> * Implemented the collection of basic metadata relating to pastes.
> * Added a visual feature that displays the expiry date in a more readable way(instead of date calculate a string like `expire in: 3 days` or `expire in: 23 hours`.
> 
> If the number of points seems too much then keep the most important ones.

All good! The more we have the better I feel

**Pull request merged**
